package co.edu.usbcali.abet;
// Generated 30/08/2015 10:05:04 PM by Zathura powered by Hibernate Tools 3.2.4.GA



/**
 * Categoria generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Categoria  implements java.io.Serializable {


     private Long idCategoria;
     private Rubrica rubrica;
     private String nombreCategoria;

    public Categoria() {
    }

	
    public Categoria(Long idCategoria, String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    public Categoria(Long idCategoria, Rubrica rubrica, String nombreCategoria) {
       this.idCategoria = idCategoria;
       this.rubrica = rubrica;
       this.nombreCategoria = nombreCategoria;
    }
   
    public Long getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Long idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Rubrica getRubrica() {
        return this.rubrica;
    }
    
    public void setRubrica(Rubrica rubrica) {
        this.rubrica = rubrica;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }




}


