package co.edu.usbcali.abet;
// Generated 30/08/2015 10:05:04 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Curso  implements java.io.Serializable {


     private Long idCurso;
     private Docente docente;
     private Materia materia;
     private PeriodoAcademico periodoAcademico;
     private String nombreCurso;
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);
     private Set<ListaSepia> listaSepias = new HashSet<ListaSepia>(0);
     private Set<OutcomePorCurso> outcomePorCursos = new HashSet<OutcomePorCurso>(0);
     private Set<RubricaPorCurso> rubricaPorCursos = new HashSet<RubricaPorCurso>(0);

    public Curso() {
    }

	
    public Curso(Long idCurso) {
        this.idCurso = idCurso;
    }
    public Curso(Long idCurso, Docente docente, Materia materia, PeriodoAcademico periodoAcademico, String nombreCurso, Set<Evaluacion> evaluacions, Set<ListaSepia> listaSepias, Set<OutcomePorCurso> outcomePorCursos, Set<RubricaPorCurso> rubricaPorCursos) {
       this.idCurso = idCurso;
       this.docente = docente;
       this.materia = materia;
       this.periodoAcademico = periodoAcademico;
       this.nombreCurso = nombreCurso;
       this.evaluacions = evaluacions;
       this.listaSepias = listaSepias;
       this.outcomePorCursos = outcomePorCursos;
       this.rubricaPorCursos = rubricaPorCursos;
    }
   
    public Long getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Long idCurso) {
        this.idCurso = idCurso;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }
    public Set<ListaSepia> getListaSepias() {
        return this.listaSepias;
    }
    
    public void setListaSepias(Set<ListaSepia> listaSepias) {
        this.listaSepias = listaSepias;
    }
    public Set<OutcomePorCurso> getOutcomePorCursos() {
        return this.outcomePorCursos;
    }
    
    public void setOutcomePorCursos(Set<OutcomePorCurso> outcomePorCursos) {
        this.outcomePorCursos = outcomePorCursos;
    }
    public Set<RubricaPorCurso> getRubricaPorCursos() {
        return this.rubricaPorCursos;
    }
    
    public void setRubricaPorCursos(Set<RubricaPorCurso> rubricaPorCursos) {
        this.rubricaPorCursos = rubricaPorCursos;
    }




}


